### PR TITLE
Test lesson

### PR DESCRIPTION
**Pull request by haesleinhuepf**
Hey @tischer ,

preparing our Zoom meeting on Monday, I just created a test module and added figures and activities. You should not merge this into master, but if you have time, I would love to see how it renders. I can't render on my system because I don't have the necessary software and lack of time to figure out how to get it.
image

Thanks!

Cheers,
Robert

### CODE REVIEW

**Comment by tischi** [comment]
@haesleinhuepf 
This is the only way I know how to preview how it would render:
https://github.com/NEUBIAS/training-resources/blob/master/CONTRIBUTING.md#building-locally
I did not try it for a long time myself. 
Should I try to get this running on my computer locally?

@tobyhodges 
Could you help here as well?

**Comment by tobyhodges** [comment]
@haesleinhuepf if you enable GitHub Pages on your repository (in Settings -> Options, choose to build from master branch), you'll be able to see the built pages from your repository at https://haesleinhuepf.github.io/training-resources/. You may need to commit some minor change after activating Pages to trigger the page build, though.

**Comment by tischi** [comment]
@haesleinhuepf could we either merge or delete this PR? I am always a bit distracted, because I think I have to do something here :-)

**Comment by haesleinhuepf** [comment]
sure :-)

**Pull request closed without merging**
