### PR TITLE
Skeletonization

### PR DESCRIPTION
**Pull request by AnniekStok**
Hi @tischi,
this is the first version of the skeletonization module. Please let me know what you think. Thanks!

### CODE REVIEW

**Comment by tischi** [comment]
@AnniekStok I will just merge it and then we can all have a look on the website.

**Comment by AnniekStok** [comment]
@tischi 
it's still the old version of skeletonization that is online now because I could not push my changes yesterday. I tried again but I am still getting this error: 
 ! [rejected]        skeletonization -> skeletonization (non-fast-forward)
error: failed to push some refs to 'https://xxxxx@github.com/NEUBIAS/training-resources.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.

It seems I have to pull this specific branch, not master? How do I avoid that this will overwrite my local changes?

**Comment by AnniekStok** [comment]
Should I try this or will that mess things up? 
https://www.janbasktraining.com/community/devops/git-push-rejected-non-fast-forward#:~:text=Git%20push%20rejected%20non%2Dfast%2Dforward%20means%2C%20this%20error,the%20same%20branch%20as%20you.

**Comment by AnniekStok** [comment]
I wonder if this [#307](https://github.com/NEUBIAS/training-resources/commit/3a649be7d0a552908442e6f3a25302371ce17c00) is the commit that is the cause of me being behind on my local branch? Even though I did run this before making the changes in the skeletonization branch:
git checkout master
git pull 
git checkout skeletonization
git merge master... 
I thought that should fix it but I am somehow still behind on the branch and a little confused 😅

**Comment by tischi** [comment]
Usually this is not an issue, I would just do

```
1. git checkout skeletonization
2. git checkout skel_backup # just to be save so you have your things in another branch, but should not be necessary
3. git checkout skeletonization
4. git pull
```

**Comment by tischi** [comment]
> I thought that should fix it but I am somehow still behind on the branch and a little confused 

I think you have to `pull` within the `skeletonization` branch (see above).

**Comment by AnniekStok** [comment]
And then also merge? Just pulling within skeletonization branch gives me this:

remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 57 (delta 27), reused 32 (delta 13), pack-reused 0
Unpacking objects: 100% (57/57), done.
From https://github.com/NEUBIAS/training-resources
   0d3302e..dbda461  master        -> origin/master
   6b9ad4a..e2379e0  output_saving -> origin/output_saving
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> skeletonization

But I still cannot push :/

**Comment by tischi** [comment]
@AnniekStok short zoom? I am in the usual image analysis zoom that we use on fridays

**Pull request merged**
