### PR TITLE
Review spatial calibration

### PR DESCRIPTION
**Pull request by tischi**

### CODE REVIEW

**Comment by tischi** [comment]
@grinic 

Thank you for the changes, I modified them a little bit...

Could you have a look whether this is still all correct?

The part where we _modify_ the spatial calibration of an image and _save_ it does not really fit the flow and it becomes a bit much. As @manerotoni suggested, this seems to better fit to the _second_ activity of this module. Would you mind adding  it there?!

I can take care of removing it from the first activity.

**Comment by grinic** [comment]
@tischi this is now done. I already removed the "voxel size change" from activity 1, and changed the `_modules/spatial_calibration.md` file to include the python implementation of activity 2.

**Comment by grinic** [comment]
Also, I removed the saving part of the activity, it didn't seem to be very useful, as we didn't read it back...

**Comment by tischi** [comment]
@grinic 

Thanks a lot! A few more suggestions.

------


For printing the image metadata I would go for this pattern:

```
print("Shape: ", image_cal.shape)
print("Axes: ", axes_image_cal)
print("Scale: ", voxel_size_image_cal)
print("Units: ", units_image_cal)
```

What do you think? If you agree, could you change it in 2nd activity at all places accordingly? 

----

I think saving the image with the changed voxel size is good, because then we can open it in Fiji to check that it worked. If you agree, could you please add to the 2nd activity saving the image after changing the voxel calibration?

**Comment by tischi** [comment]
@grinic 
I simplified act2: since we are already changing the voxel size of the 3D image I don't think it was necessary to change it again before saving it. From my side this could be merged now. Are you OK with these changes?

@manerotoni 
It would be nice if the image of the 3D nucleus contained a whole nucleus and not just some small part of it. Do you remember why we did that? Do we have a better image?
If we don't find a quick solution I think we should open an issue to replace the 3D nucleus image by a better one at some point.

**Comment by grinic** [comment]
The changes look good to me!

**Comment by manerotoni** [comment]
> @manerotoni
> It would be nice if the image of the 3D nucleus contained a whole nucleus and not just some small part of it. Do you remember why we did that? Do we have a better image?
> If we don't find a quick solution I think we should open an issue to replace the 3D nucleus image by a better one at some point.

There was no reason, it was just one image at hand. I will create the issue to replace with a complete 3D image of a nucleus.

**Pull request merged**
