### PR TITLE
Splitting slice viewing

### PR DESCRIPTION
**Pull request by AnniekStok**
Working on splitting the slice viewing module in two separate modules:
1. N-dimensional image basics, focusing on viewing data in different dimensions (multiactivities for ImageJ and Napari GUI)
2. volume slicing and subsetting, focusing on 3D -> 2D slicing, and subsetting with an ROI + image > duplicate (only ImageJ for now, but I think slicing numpy arrays in the Napari console might actually be easier, can add this later as well). First activity uses isotropic data, the second anisotropic data. I added new synthetic sample images for the exercises.

### CODE REVIEW

**Comment by manerotoni** [comment]
Somehow it still has a conflict in the volume_slicing_act1
This is strange as you already performed the merge with master.

**Comment by manerotoni** [comment]
The exercise preface looks completely different

act1:
<<<<<<< HEAD
### Slice different planes of a 3D image
- Open the multidimensional image [xyz_16bit_t1-head.tif](https://github.com/NEUBIAS/training-resources/raw/master/image_data/xyz_16bit_t1-head.tif).
- Explore the 3D volume in XY, XZ, and YZ views.
- Create a slice at Z = 60
- Create a slice at X = 135
- Create a slice at Y = 160
- Create a diagonal slice 
=======
#### Explore slicing of a 3D image
  - Open the 3D image [xyz_8bit__chromsomes.tif](https://github.com/NEUBIAS/training-resources/raw/master/image_data/xyz_8bit__chromosomes.tif).
    - The data shows chromosomes wrapped around a spherical(!) nucleus; i.e. the data should look similar from all directions.
    - View (slice) the data in XY, YZ, and XZ.
    - Observe that the image is calibrated.
    - Observe that the rendering in XZ and YZ is deformed without taking the calibration into account.
  - Open the 3D multi-channel image [xyzc_8bit_beads_p_open.tif](https://github.com/NEUBIAS/training-resources/raw/master/image_data/xyzc_8bit_beads_p_open.tif).
    - Explore different options for rendering the channel dimension (e.g. gray-scale, color, composite).
    - View the properties of this image. Are the XYZ dimensions isotropic or anisotropic?
    - Subset the data such that a new image is created that contains only the green channel.
    - Reslice the green channel, such that the bead is shown from the side.
      - Explore different options of dealing with the anisotropy.
>>>>>>> master

act2: 
<<<<<<< HEAD
### Subset a 3D image
  - Open the 3D multi-channel image [xyzc_8bit_spheres.tif](https://github.com/NEUBIAS/training-resources/raw/master/image_data/xyzc_8bit_spheres.tif).
    - View the dimensions and properties of this image. Are the XYZ dimensions isotropic or anisotropic?
    - Subset the data such that a new image is created that contains only the green channel and the region containing the green sphere.
    - Create an YZ slice of the green sphere image, and explore different options of dealing with the anisotropy.
=======
#### Apply reslicing to view a 3D object from different angles
- Open the multidimensional image [xyz_16bit_t1-head.tif](https://github.com/NEUBIAS/training-resources/raw/master/image_data/xyz_16bit_t1-head.tif).
- Reslice the image from different directions, such that you can view the image stack from the side, from the top, and from the front.
- How do you think one could see the head from 3/4 view? Tip: there is a function called ‘rotate’ in ImageJ ([Image > Transform > Rotate]).
>>>>>>> master

**Comment by manerotoni** [comment]
Could you fix it first?

**Comment by tischi** [comment]
HEAD are typically your latest changes...

**Comment by manerotoni** [comment]
Hi I am working on fusing my changes with yours. I close this pull request and I have created a new one with all the changes.
I would like to keep the N-dimensonal module and just adding the napari python code to it and an additional activity.

**Comment by AnniekStok** [comment]
Yes the activities are different because I was splitting the modules. Keeping head should be fine, I thought I did that but it still seems to have gone wrong somehow. Thank you for implementing the changes!

**Pull request closed without merging**
