### PR TITLE
Multiactivities for volume slicing module

### PR DESCRIPTION
**Pull request by AnniekStok**
@tischi I replaced activities and exercises by multiactivities. All source files are in the includes/activities folder (I suppose the exercises folder can therefore be deleted, nothing for this module refers to it anymore, but I still left it in for now). I hope I understood everything correctly, otherwise I can of course correct it.

### CODE REVIEW

**Comment by tibuch** [comment]
I can render the website locally and everything looks good to me.

I would vote to remove the exercise folder, otherwise we or others might get confused in the future. What does @tischi think?

**Comment by tischi** [comment]
I had a very brief look and it seems there is a subfolder called `_includes/volume_slicing/activities`.
@tibuch I guess you mean to remove the `activities` subfolder? So we have everything under `_includes/volume_slicing` without any further subfolders?  I think this is a good idea. 
@AnniekStok what  do you think?

**Comment by tibuch** [comment]
Indeed! Now that we only have activities we don't need a specific sub-directory. Sounds good to me.

**Comment by tischi** [comment]
@AnniekStok could you please make those changes such that we can merge your PR?

**Comment by AnniekStok** [comment]
I might actually be able to do it via TeamViewer tomorrow, it still gives me a few seconds of access per hour. Otherwise I will download everything to my new computer and try from there if it's not possible to fix it on github directly (I haven't used github much outside of this project, and I am still not super good with it so I always follow exactly my notes that are on the EMBL computer)

**Comment by tischi** [comment]
There is no rush with this!
Just take your time!

**Comment by AnniekStok** [comment]
I think it should be fixed now!

**Comment by tischi** [comment]
@AnniekStok 
Looks good! Thanks!
I would vote for renaming `ImageJ Python` to `ImageJ Jython` to avoid confusion with `pyImageJ`.

**Comment by tischi** [comment]
Hi @AnniekStok could you do the final changes such that we can merge this?

**Comment by AnniekStok** [comment]
I just pushed the last changes (changing the name from Python to Jython)

**Comment by tischi** [comment]
Thanks a lot for putting the time and work into this!

**Pull request merged**
