### PR TITLE
Improve spatial calibration figure and concept map

### PR DESCRIPTION
**Pull request by tischi**
Hi @manerotoni,

Could you have a look whether you agree with the proposed changes?

This is how it looks like now:

image

image

### CODE REVIEW

**Comment by manerotoni** [comment]
Hi tischi,
I have a few suggestion. 
In the figure you also multiply index*spacing but in the concept map you refer to value and calibration. To me an index is an integer value so using value is redundant. In the concept map if you want to keep calibration add spacing as an extra term/synonim. (calibration, spacing) 

The arrow in the figure is not clear that it refers to the pixel coordinate. Could you draw a small square around the pixel?

**Comment by tischi** [comment]
> In the figure you also multiply index*spacing but in the concept map you refer to value and calibration. 

Should we also call it `calibration` in the figure instead? The thing is that if you look at the whole figure there is also a drawing for "spacing. "

image

What about we remove the word "spacing" entirely from the figure and just keep `dx` and `dy`?

> To me an index is an integer value so using value is redundant. 

The "value" refers to the gray value of the pixel; shall we rename it? We always make the point that a pixel has two properties, its indices and its value.

**Comment by tischi** [comment]
> The arrow in the figure is not clear that it refers to the pixel coordinate. Could you draw a small square around the pixel?

One would not be able to see it. We had a zoom in overlayed, but that was confusing...maybe we should take a picture with less pixels? We could downsample this image!

**Comment by manerotoni** [comment]
> > The arrow in the figure is not clear that it refers to the pixel coordinate. Could you draw a small square around the pixel?
> 
> One would not be able to see it. We had a zoom in overlayed, but that was confusing...maybe we should take a picture with less pixels? We could downsample this image!

I would draw a bigger pixel or just a dot. Downsampled image is an option. Or leave it like this.

**Comment by tischi** [comment]
@manerotoni 

Thanks! I think downsampled version would be most appropriate.

Could you please also comment on some things that I said a bit higher up (about the spacing a.s.o)?

**Comment by manerotoni** [comment]
I prefer dx and dy. And yes either spacing or calibration. Spacing I never use, I use pixel-dimensions, pixel-size. Some people write from the center distance, but you can also view as the length of the square. None 

Now I get for values what it means. May be write  "intensity value" here or leave it as it is. I think it is clear that a pixel has 2 attributes.

**Pull request merged**
