### PR TITLE
Automated Thresholding skimage napari

### PR DESCRIPTION
**Pull request by sebgoti**
Observations:
 - How many threshold algorithms should we show?

### CODE REVIEW

**Comment by tischi** [comment]
@sebgoti I changed the PR title, is that correct?

**Comment by sebgoti** [comment]
Yes, this is correct 👍🏼

**Comment by sebgoti** [comment]
@tischi I think this is ready to merge :)

**Comment by manerotoni** [comment]
Checked the PR and fixed some minor errors. Ready to merge!

**Pull request merged**
