### PR TITLE
Review multi-dimensional images

### PR DESCRIPTION
**Pull request by tischi**
Hi,

@grinic @manerotoni @tibuch @AnniekStok 

I am looking at this module, as I will have to teach it :-)
 
First question: should I also teach the drag&drop pure Napari activity? Or only the skimage one? I would prefer to only do the skimage implementation.

### CODE REVIEW

**Comment by tischi** [comment]
`_includes/multidimensional_images/multidimensional_images_act1_skimage_napari.py` is now **very similar** to the spatial calibration activities. But maybe that's OK, then this is just a little repetition?

--------

Do we want students to understand such code? 

```
# %%
# compute aspect ratio
print(scales)
aspect_ratio = [s/scales[2] for s in scales]
print(aspect_ratio)
```

It is useful but it will take a long time to explain it... I actually think that could be removed from this activity as one can see the aspect ratios simply by looking at the output of `print(scales)`

**Comment by tischi** [comment]
@manerotoni  do you know what this is doing?

```
# %%
# Change order of axis (swap T and Z)
napari_viewer.dims.order = (1, 0, 2, 3)
```

It did not seem to have any effect when I executed it...

**Comment by manerotoni** [comment]
> @manerotoni do you know what this is doing?
> 
> ```
> # %%
> # Change order of axis (swap T and Z)
> napari_viewer.dims.order = (1, 0, 2, 3)
> ```
> 
>  * [ ]  It did not seem to have any effect when I executed it...

Hi  @tischi,
and @AnniekStok explained it is the order how Naperi views the data. It is important as you may have a time projection instead of Z projection. It could be that I made an error in the code , but this should be the effect. 
Naperi may read T as Z

**Comment by manerotoni** [comment]
I checked and the transform is fine and it does what it  should in 3D. 
However, the exercise is confusing. The image is read in the correct order, so you do not need to swap dimensions here. 
When you do 3D you have in the slide 31 time points. 

My suggestion would be to remove the dimension swap as it is not needed here. There are cases where it is needed depending on the format of data you read in.

**Comment by tischi** [comment]
Is there a way to within the napari viewer see what the "time" axis is? I don't think so, right?

...and, @manerotoni, please also check my two questions further up in this issue.

...and does anyone know why I don't have a 3D rendering button in my napari?

**Comment by manerotoni** [comment]
> ```
> # %%
> # compute aspect ratio
> print(scales)
> aspect_ratio = [s/scales[2] for s in scales]
> print(aspect_ratio)
> ```
> 
> It is useful but it will take a long time to explain it... I actually think that could be removed from this activity as one can see the aspect ratios simply by looking at the output of `print(scales)`. My vote would be to remove the above code.

When designing the activity I had the same problem. I think you can remove it and mention that the aspect ratio is not yet correct, but we have an extra activity for it on aspect ratio.

May be leave the code as comment? Not very elegant but useful

**Comment by tischi** [comment]
@manerotoni could you post a screenshot here for where you find the volume rendering button in napari?

**Comment by manerotoni** [comment]
This is when it is in 2D

image

This is how it looks in 3D

image

Ctrl-Y, It is the standard way of viewing data in 3D.

**Comment by tischi** [comment]
Hi @AnniekStok and @manerotoni,

I further simplified the activities a little bit.

I think the example image for act4 is not great as it just shows two blobs.
- [ ] Do we have a 5D image that show a bit more biological content? 
That would make it much easier to appreciate when the axes orders are correct.

**Comment by manerotoni** [comment]
Hi @tischi, 
pull master and look at `xyzct_16bit__metaphase_eb3_cenpa.tif `

**Comment by tischi** [comment]
❤️ it!! Thanks @manerotoni!!!

**Comment by tischi** [comment]
I think this can be merged now.

**Pull request merged**
