### PR TITLE
added exercise for EM and padding details

### PR DESCRIPTION
**Pull request by maulakhan**
@tischi can you please review it?

### CODE REVIEW

**Comment by maulakhan** [comment]
@tischi can you please review the new changes?

**Comment by tischi** [comment]
Hi @maulakhan 

Thanks a lot for the nice work!

I still found a couple of issues:

image

The figure legend does not match the figure anymore, because we changed the colors.


-------------

image

1. We should add some information on which image to work. Something like: "Open the image mentioned ..."? Or just copy the link there again, for the students that would be the best!
2. I do not understand the sentence _"The expected result from manual thresholding should be [xy_8bit_binary__noisy_two_nuclei_close.tif](https://github.com/NEUBIAS/training-resources/raw/master/image_data/xy_8bit_binary__nuclei_very_noisy_close.tif)"_, what do you mean by "expected result" and what do you mean by "manual thresholding"? Could you maybe try to phrase it differently? Maybe you want to say: "Try to segment image XYZ into foreground and background; the result should look similar to ABC"? But I am not sure, I might be completely off as I am not sure what you were aiming to say 😃 ...and I also don't understand why you link to the input image?
3. `Radius 1: Lower Threshold Level = 38` maybe `Lowest` rather than `Lower`?
-----------

image

1. Also, here I think we should add some information on which image to work on. Something like: "Open the image mentioned ..."? Or just copy the link there again, for the students that would be the best!
1. Solution: This is wrong: 255 is not the bit depth, the bit depth is unsigned 8-bit: _pixel values can exceed 255 which is current bit depth of input image_ .Probably you want to rephrase using something with: "maximal value of the current bit depth"

----

I fixed some grammar issues, please _pull_ before you work on the above issues.

**Comment by tischi** [comment]
In fact, I was not precise either. 
I think this is the correct way to state it:
- The bit depth of the unsigned 8-bit datatype is 8 (and not 255).
- The maximum value of the unsigned 8-bit datatype is 255.

Would you agree?

**Comment by maulakhan** [comment]
yes I agree with bit depth answer.

**Comment by tischi** [comment]
@maulakhan Thanks! I tried to still improve the text in the exercises a bit. Could you please have a look whether you like and and whether I may have introduced some mistakes? 
I am sorry for being so pedantic about this, but the issue is that the students will be alone in breakout rooms when doing the exercises, thus we cannot easily help them, thus the exercises really have to be absolutely totally clear and waterproof.

**Pull request merged**
