### PR TITLE
Template Adjustments

### LINKED ISSUE #23: File endings of scripts
@tobyhodges 

The file endings in below folder are all .md

- https://github.com/NEUBIAS/training-resources/blob/master/_includes/binarization/activities/binarization_imagejmacro.md

For scripts, would it be OK to use the "native" file endings such as `binarization.ijm` instead?
This would allow to use those files directly in the software.

### LINKED ISSUE #55: exercises and solutions
@tobyhodges 
May we ask your advice?

@manerotoni and I have discussed again the structure of the exercises and activities. We are thinking now that it would be nice to have the question part of the exercise language independent and then only have language specific solutions. 

Along those lines, do you think it could be ok to put the solutions directly into the module.md file rather than linking to language specific solution files? 

Main advantage, I think, it would be easier to contribute a new module (and also update solutions if the questions change) if one just needs to modify one file rather than multiple files distributed across different folders.

### LINKED ISSUE #57: markdown activities still supported as well?
@tobyhodges @manerotoni 
We just discussed that in the activities folders would be just plain text scripts, like `binarise.py`.
However I found this one: https://github.com/NEUBIAS/training-resources/blob/master/_includes/binarization/activities/binarization_knime.md
Would that still work?

### PR DESCRIPTION
**Pull request by tobyhodges**
Closes #57 
Closes #55 
Closes #23 

This makes the changes to the module template as discussed previously.

- #55 : you now have a separate _Assessment_ section at the end, which is for a generic assessment of understanding of the central concept in the module. `exercises_preface` has been removed and replaced by `assessment`.
- #57 : the `activities` field in the YAML of a module file is now a "list of lists," with each entry containing three items: the name of the platform (e.g. `"ImageJ Macro"`), the path to the activity file/script (e.g. `"/binarization/activities/binarization.py"`), and a language name for syntax highlighting (e.g. `"python"`).
  - activity instructions that should not be displayed as code blocks should be provided with the language identifier "markdown" for their content to be rendered correctly.
  - I changed the format of the `exercises` field to match this, even though those entries only have two parameters each.
- #23 : as shown by the renaming of `"/binarization/activities/binarization_python.md"` to `"/binarization/activities/binarization.py"`, you can change the extensions of the activity scripts as you wish. Just be sure to make the corresponding adjustment to the filename in the YAML of the relevant module file.

Example YAML header after these changes are applied:

```yaml
title:     Image binarization
layout:    module
prerequisites:
  - "[Basic properties of images and pixels](pixels)"
objectives:
  - "Describe the relationship between an intensity image and a derived binary image"
  - "Apply a threshold to distinguish foreground and background pixels"
motivation: >
  Very often, one wants to detect objects or specific regions in images. Typically, the first step to achieve this aim is to distinguish so-called background pixels, which do not contain objects or interesting regions, from foreground pixels, which mark the areas of interest. The foreground regions can than be further processed, e.g to detect objects or perform measurements.
concept_map: >
  graph TD
    PV("Pixel values") --> BA(Binarization algorithm)
    BA --> BPV("Binarized pixel values")
    BPV --> BG("Background (0)")
    BPV --> FG("Foreground (1)")

figure: /figures/binarization.png
figure_legend: Image before and after binarization by applying a threshold.

activity_preface: >
  Open an image and binarize it by applying a threshold.

activities:
  - ["ImageJ GUI", "binarization/activities/binarization_imagejgui.md", "markdown"]
  - ["ImageJ Macro", "binarization/activities/binarization_imagejmacro.md", "java"]
  - ["Jython", "binarization/activities/binarization_jython.md", "python"]
  - ["MATLAB", "binarization/activities/binarization_matlab.md", "matlab"]
  - ["KNIME", "binarization/activities/binarization_knime.md", "markdown"]
  - ["Python", "binarization/activities/binarization.py", "python"]

exercises:
  - ["ImageJ GUI", "binarization/exercises/binarization_imagejgui.md"]
  - ["ImageJ Macro", "binarization/exercises/binarization_imagejmacro.md"]
  - ["Jython", "binarization/exercises/binarization_jython.md"]
  - ["MATLAB", "binarization/exercises/binarization_matlab.md"]

assessment: >

  ### Fill in the blanks

    - Pixels in a binary image can have maximally ___ different values.
    - If the threshold is larger than the maximal pixel value in the intensity image, all pixels in the binary image have a value of ___.

learn_next:
  - "[Algorithms to automatically determine a threshold value](auto_threshold)"
  - "[Finding objects in a binary image](connected_components)"

external_links:
  - "[Wikipedia: Binary image](https://en.wikipedia.org/wiki/Binary_image)"
```

### CODE REVIEW

**Comment by tischi** [comment]
I think this looks 😍 !
@manerotoni What do you think?

Few questions: 

1. Within the `assessment` section can we use syntax like below for drop-down solutions? 
(obviously without the "language part").
Or should we use another syntax?

```
solutions:
  - language: "Jython"
    solution: |
      code
      goes
      here
    highlighting: "language-python"
```

2. Should we have a `keypoints` section as well?

**Comment by tobyhodges** [comment]
1. The `assessment` field will be inserted "as-is" into the page and rendered from the Markdown, but is not set up to include any solution block by default. 
    - My understanding was that you would use this _Assessment_ section only to check the learners' grasp of the concept being taught i.e. that these would be tasks without a practical/programming element and therefore wouldn't need platform-specific solutions? Otherwise they may be put into the _Exercises_ section as well... 
    - I suppose I could add a `solution` field to `assessment`, which would be inserted beneath the assessment text, if you like? But that would be a platform-agnostic solution (to go with the platform-agnostic question...) Platform-specific solutions would take some extra work to implement.
2. Yes, `keypoints` can be included as a list like `objectives`.

**Comment by manerotoni** [comment]
why can't we use directly the decorators(?) to assign solutions etc. You can also have language specific syntax within.   

```   
 > ## Solution
 >   - There is only one correct threshold value in order to convert an intensity image into a binary image. **False**
 >   -  Binary images are always unsigned 8-bit where the foreground is 255. **False**
 {: .solution}
```

or 
```
> ## Solution
> ```python
> from ij import IJ, ImagePlus
> from ij.plugin import Thresholder
> # image is xy_8bit__two_cells.tif
> inputImage = IJ.getImage() #get Current open Image
> IJ.setRawThreshold(inputImage, 5, 255, None)
> binaryImage = ImagePlus('Binary image 2 nuclei', Thresholder.createMask(inputImage))
> binaryImage.show()
> IJ.setRawThreshold(inputImage, 4, 4, None)
> binaryImage_boundary = ImagePlus('Binary boundary', Thresholder.createMask(inputImage))
> binaryImage_boundary.show()
> IJ.setRawThreshold(inputImage, 44, 255, None)
> binaryImage_brightdots = ImagePlus('Binary bright dots', Thresholder.createMask(inputImage))
> binaryImage_brightdots.show()
> ```
{: .solution}
```

**Comment by tobyhodges** [comment]
You can indeed do this.

**Comment by tischi** [comment]
>  i.e. that these would be tasks without a practical/programming element and therefore wouldn't need platform-specific solutions

Exactly, that's why I said above "(obviously without the "language part")". 

But the assessment still need solutions 😃 and I was wondering how to add them. I am fine with the way the @manerotoni found. In fact, if that's the standard way of doing it, that's probably the best. I just was curious because you proposed another syntax in this issue: https://github.com/NEUBIAS/training-resources/issues/55 

@tobyhodges If you think `> ## Solution` is the way to go **for general language-agnostic comprehension solutions** I am fine with this PR being merged by you! Thanks a lot for the work you put into it!

**Comment by tobyhodges** [comment]
Let's do that for now. If you find that adding the solution blockquotes is too fiddly while maintaining correct indentation in the YAML, ping me and I can add something to the template to abstract away that formatting.

**Pull request merged**
