### PR TITLE
Connected components

### PR DESCRIPTION
**Pull request by manerotoni**
Create multi activity

### CODE REVIEW

**Comment by manerotoni** [comment]
Write ome_tiff

**Comment by manerotoni** [comment]
Hi @tischi,
this is ready for review. You can review and check it.

**Comment by grinic** [comment]
All looks good, I just changed a small changed to have all the imports at the beginning of the notebook (best practice). Ready to merge if you agree with the changes.

**Comment by tibuch** [comment]
This closes #508.

**Pull request merged**
