### PR TITLE
Simplify and improve the all modules pages

### PR DESCRIPTION
**Pull request by tischi**
Hi,

I made some modifications to our module overview page.

Currently, if one zooms out it looks like this:

image

After the changes in this PR it looks like this:

image

Doing this I also got rid of the Workflow and Scripting and Draft headings and instead added those terms as title prefixes, because:

1. The rendering of the all modules page looks nicer without those headings
2. It simplifies the code for creating this page a lot and thus will make this easier to maintain
3. Any hierarchy is bound to break anyway ;-)
4. It was not my original motivation, but a big advantage, imho, is that one can now put the workflows at the natural place where one would normally teach them

### CODE REVIEW

**Comment by tibuch** [comment]
I :heart: the idea! 

Would it be possible to set a min-width for the boxes? Currently the min-width seems to small. If I render it and show it on half my screen it looks like this:
image

If I reduce the window with to a quarter it looks good again:
image

**Comment by tischi** [comment]
Hi @tibuch,

Thanks for having a look!

Interestingly, in my screenshot the panel headings seem to be much smaller and thus I do not have the issue with the text overflowing. Maybe this also is a browser issue? Which browser did you use and does it behave the same if you use another browser?

------

We could try (one ruby www is responsive again)

in `assets/css/bootstrap.css`

```
    .panel {
      min-width: 150px; /* Adjust the value as needed */
    }
```

**Comment by tibuch** [comment]
I tried firefox and chrome and get the same behavior in both. .

The proposed change results in this:
image

**Comment by tischi** [comment]
I added some more improvements; I think it is good enough now. I will merge it and then we can improve more later.

**Pull request merged**
