### PR TITLE
Improve pixels module

### PR DESCRIPTION
**Pull request by tischi**
What do you think?

If I hear nothing by Monday noon I would merge it because I need to teach this on Monday at 14:00....

### CODE REVIEW

**Comment by manerotoni** [comment]
I am reviewing just now. Wait a sec before merging

**Review by manerotoni — COMMENTED** [review]
pixels.jpg has a yellow pixel value at 2 and 4. Is this for teaching purpose.

Is it on purpose not naming X and Y axis?

**Comment by manerotoni** [comment]
Apart my small comment you can go on and merge.

**Comment by tischi** [comment]
> pixels.jpg has a yellow pixel value at 2 and 4. Is this for teaching purpose.

🦅 👁️ ! This was a mistake, I fixed it.

> Is it on purpose not naming X and Y axis?

Sort of, yes, because in python skimage I think they call the dimensions `r` and `c`.

**Pull request merged**
