### PR TITLE
Workflow nuclei and cells segmentation

### PR DESCRIPTION
**Pull request by manerotoni**
Hi @tischi,
I went through the activity and assessment. Some typo corrections and did some modification on the legend as I felt it required more hints. 
The image I moved it up to be consistent. I would avoid subfolders if not strictly required.

### CODE REVIEW

**Comment by tischi** [comment]
Thanks @manerotoni !

I only saw that you removed the watershed subfolder [here](https://github.com/NEUBIAS/training-resources/pull/333/files#diff-8d0bd01eb2f07ddb03e2e5d20a7b4bda3a9374ac34dcfca7c7cb23cfb10ae449) but isn't data from this sub-folder is also used at other places?!

**Comment by manerotoni** [comment]
No @tischi I did not remove the folder. The watershed folder is in the watershed module.

**Comment by manerotoni** [comment]
The tif is in the main folder. It was anyway not completely correct the location as the name of the file was different in watershed (not named crop). I wonder if one should not have only the derivate data in subfolder. Maybe create a subfolder with the same name of the image? 

I think I let you decide. We should for sure check if the paths are correct.

**Comment by tischi** [comment]
I will merge and then we can check.

**Pull request merged**
