### PR TITLE
Auto threshold: Add figure and concept map

### PR DESCRIPTION
**Pull request by tischi**
I think we could add this and just show the figure to the students.
What do you think?
Please feel free to add more content.

### CODE REVIEW

**Review by AnniekStok — COMMENTED** [review]
Hi @tischi,
I think it looks good. 

Two comments:
- I saw a typo in (new) line 12 'every images'.
- It could be just me, but I was initially a bit confused with the figure, because from the second column I first interpreted the blue and orange lines as the lower and upper thresholds (forming a gate), but then realized from the third and fourth column that these are both lower thresholds and serve to show the different outcomes. Maybe a slightly different annotation using a horizontal bar marking the entire selected region would make it more clear. Not sure. I like how the figure visualizes the different situations and outcomes.

**Comment by tischi** [comment]
- [ ] We could use this to show that auto-threshold can give you all kind of results

image

image

**Comment by tischi** [comment]
@AnniekStok 

I agree with both your comments. 
Could you try to improve the figure (ppt) in this branch (pull, add, push)?

**Comment by maulakhan** [comment]
I will work on producing two images (one with intensity offset) where selecting a manual threshold would not work but automatic would

**Comment by AnniekStok** [comment]
@tischi 
I made an attempt updating the figure, I hope it helps.

**Comment by tischi** [comment]
Thanks @AnniekStok, based on your changes I tried to improve it even further (making it a bit simpler).

**Comment by maulakhan** [comment]
@tischi can you please review the activity that I added for auto_threshold

**Comment by tischi** [comment]
@maulakhan 

Thanks!

1. I merged the latest master, please pull this branch.
2. Please use two different images for the activity (showing different nuclei).

**Pull request merged**
