### PR TITLE
Installation instructions

### PR DESCRIPTION
**Pull request by stemarcotti**
Related to https://github.com/NEUBIAS/training-resources/issues/399
Any pre-merging feedback is welcome!!

1. Updated setup page to show instructions for software installation
Screenshot 2022-05-31 at 12 02 53

2. Created new module named "Tool Installation" with instructions for installing the different software
Screenshot 2022-05-31 at 12 03 14

3. The new module shows first in the drop-down menu and in the module overview
Screenshot 2022-05-31 at 12 03 36

### CODE REVIEW

**Comment by tischi** [comment]
I think this is very nice!

In terms of concept map, one could also do it around the ideas that 

"image analysis" is done with "computer" using a "tool", which needs to be "installed".

Something like this. In any case I think removing the specifics of Napari and Fiji from the concept map would be good.

Otherwise I like it. 

Thanks a lot!

**Comment by stemarcotti** [comment]
Thanks @tischi for your feedback,
I'll work on the concept map then!

**Comment by stemarcotti** [comment]
@tischi here's the new concept map following your idea, let me know if it works!
(everything tested locally before pushing :) )

Screenshot 2022-06-09 at 11 09 23

**Comment by tischi** [comment]
I think that's great!
Shall we merge or do you want to still work on something?

**Comment by stemarcotti** [comment]
happy to merge!
Do you want me to do so?

**Comment by tischi** [comment]
yes, go ahead!

**Pull request merged**
