### PR TITLE
Python morphological filters

### PR DESCRIPTION
**Pull request by grinic**

### CODE REVIEW

**Review by tibuch — CHANGES_REQUESTED** [review]
The morphological filters activity looks good to me. 

Is it intentional that measure_intensities and spatial_calibration is also part of this PR?

**Comment by grinic** [comment]
Ooops not intentional... Would this create a conflict with master? I don't know how, but can we make some fetch magic to ignore those changes at merge?

**Review by grinic — COMMENTED** [review]
change looks good to me.

**Comment by tischi** [comment]
@grinic maybe you could locally merge the latest master into this branch and see whether those changes disappear? but I think @tibuch might know some git tricks to tackle this in some other way...

**Comment by tibuch** [comment]
[PR 525](https://github.com/NEUBIAS/training-resources/pull/525) should contain only the files we want to merge. The rest is already there :slightly_smiling_face:

**Comment by tischi** [comment]
Thanks a lot @tibuch !!

Closing this one.
Merging the other one.

**Pull request closed without merging**
