### PR TITLE
added exercise

### PR DESCRIPTION
**Pull request by maulakhan**
Added image stack exercise and assessment

### CODE REVIEW

**Comment by manerotoni** [comment]
I will also have a look now. I will first merge the master into it. This avoids bad surprises when we merge this branch into master.

**Comment by AnniekStok** [comment]
@maulakhan, yes cool it works now!
I think showcasing the autothresholder like this is good. In practice I always use the thresholder window, so I thought maybe to mention to the students that they can use this menu for both manual and autothreshold methods? 
image
I still have a question about the log window, I actually still don't see 91 somehow, mine looks like this:
image

**Comment by manerotoni** [comment]
Hi @maulakhan,
it looks all good to me. Great job. Here some minor suggestions:
**Concept map**
The concept map I would change to 
```
    I("Image") --> H("Histogram")
    H -- algorithm --> T("Threshold value")
```

image

** Threshold window simple**

I also agree with @AnniekStok that in the activity one should show the threshold window first and how to change the threshold there. For instance with the option [Over/under]. 

The autothresholder is more of a benchmark tool for many threshold at once. It is hard to see in detail how the results are.

In the activity mention `stack histogram` option in the Fiji-GUI activity. This will be used for the exercise. 

** Exercise preface**
The `stack histogram` naming may be specific to Fiji. For a more generic naming I would use
> Select any threshold method and observe the differences in segmentation when you use the histogram computed from all images in the 3D stack.

** follow up material**
For the link you can be more specific where it lead "Imagej.net Auto-threshold"

**Comment by manerotoni** [comment]
Hi @AnniekStok,
> I still have a question about the log window, I actually still don't see 91 somehow, mine looks like this:

my guess is that some algorithms are iterative.  When you have just background the algorithm may not find a solution. This is posted in the log window. In fact when you just copy the first slice and apply the threshold you exactly get the same log message.

**Comment by AnniekStok** [comment]
Ah, yes. I tried again and I can see the threshold values now! My bad!

**Comment by maulakhan** [comment]
The concept map I would change to 
```
    I("Image") --> H("Histogram")
    H -- algorithm --> T("Threshold value")
```
image

- DONE

**Threshold window simple**

I also agree with @AnniekStok that in the activity one should show the threshold window first and how to change the threshold there. For instance with the option [Over/under]. 

- I can explain this during activity as it already includes thresholding applet

The autothresholder is more of a benchmark tool for many threshold at once. It is hard to see in detail how the results are.

In the activity mention `stack histogram` option in the Fiji-GUI activity. This will be used for the exercise. 

- I will mention this too, thanks

**Exercise preface**
The `stack histogram` naming may be specific to Fiji. For a more generic naming I would use
> Select any threshold method and observe the differences in segmentation when you use the histogram computed from all images in the 3D stack.

- FIXED

**follow up material**
For the link you can be more specific where it lead "Imagej.net Auto-threshold" 

- FIXED

**Pull request merged**
