### PR TITLE
Thresholding 

### PR DESCRIPTION
**Pull request by tischi**
I simplified the activity: 
- removed the MATLAB data type discussion
- removed the [ Manual Threshold ... ]
- removed the part where we only segment the brighter nucleus as this is not good practice and we are sending the wrong message here

- [ ] I did not manage to make the central pixel in the figure black, can you?

### CODE REVIEW

**Comment by tischi** [comment]
We could also add:

- [ ] measure background noise (mean + sdev) and compute a threshold based on this.

**Comment by tischi** [comment]
As I was working more on the binarization module in [this napari PR](https://github.com/NEUBIAS/training-resources/pull/167), this may result now in merge conflicts.

Maybe we first merge the napari PR and then see...

**Comment by manerotoni** [comment]
> As I was working more on the binarization module in [this napari PR](https://github.com/NEUBIAS/training-resources/pull/167), this may result now in merge conflicts.
> 
> Maybe we first merge the napari PR and then see...

Merged and implemented some of your comments

**Comment by manerotoni** [comment]
> We could also add:
> 
>     * [ ]  measure background noise (mean + sdev) and compute a threshold based on this.

I added a third activity. Could you check if it is what you meant?

**Pull request merged**
